name: Unit Test

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags:
      - "v*"

jobs:
  unit-test:
    name: Run Unit Test
    runs-on: windows-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Test
        run: npm run test
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
